services:
  - type: web
    name: learning-log
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn ll_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ll_project.settings
      - key: PYTHON_VERSION
        value: 3.13
